name: fakevoicetest
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - ipykernel
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - librosa
  - pywavelets
  - pillow
  - pip
