name: fakevoice
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - ipykernel
  - numpy
  - librosa
  - pywavelets
  - pillow
  - matplotlib
  - pandas
  - scikit-learn
  - pip
  - pip:
      - torch==2.8.0+cu126
      - torchvision==0.23.0+cu126
